spring.application.name=demo
#spring.datasource.url=jdbc:mysql://localhost:3306/springbootjpa?characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=123456
spring.datasource.url=jdbc:h2:file:./data/db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.thymeleaf.cache=false
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
